#!/usr/bin/env node
// Build step for the HTML5 web port.  No dependencies, Node >= 18.
//
//   node web/tools/build.mjs            regenerate everything
//   node web/tools/build.mjs --check    fail if committed generated files are stale (CI)
//
// It produces, from the shared ../assets tree and the Python sources:
//   web/js/constants.generated.js   gameplay numbers scraped from src/games/*.py + src/engine.py
//   web/js/assets.generated.js      curated, pre-grouped asset manifest (mirrors the Python
//                                   discovery/filter rules in src/games/*.py)
//   web/js/sw-precache.generated.js flat file list + CACHE_VERSION for the service worker
//   web/CREDITS.html                concatenated per-theme credits.txt / copyright.html
//   web/assets/**                   copy of every asset the manifest references (git-ignored)

import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const WEB = path.resolve(HERE, "..");
const ROOT = path.resolve(WEB, "..");
const ASSETS = path.join(ROOT, "assets");
const OUT_ASSETS = path.join(WEB, "assets");
const CHECK = process.argv.includes("--check");

const GENERATED_HEADER =
  "// GENERATED by web/tools/build.mjs -- do not edit by hand.\n" +
  "// Regenerate with `node web/tools/build.mjs`; CI checks it is current.\n\n";

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------
const readText = (p) => fs.readFileSync(p, "utf8");
const listDir = (p) =>
  fs.existsSync(p) ? fs.readdirSync(p).sort((a, b) => a.localeCompare(b)) : [];
const isFile = (p) => fs.existsSync(p) && fs.statSync(p).isFile();
const rel = (abs) => path.relative(ASSETS, abs).split(path.sep).join("/");
const stem = (name) => name.replace(/\.[^.]+$/, "");
const ext = (name) => (name.match(/\.[^.]+$/)?.[0] ?? "").toLowerCase();

const IMG_EXT = new Set([".png", ".jpg", ".jpeg"]);
const referenced = new Set(); // asset-relative paths pulled into the manifest

function ref(relPath) {
  referenced.add(relPath);
  return relPath;
}

/** Files in a theme dir that Python's Activity.theme_images() would return. */
function themeImages(themeDir, { extensions = [".jpeg", ".jpg", ".png"], excludePrefixes = ["fond", "logo", "cache"] } = {}) {
  return listDir(themeDir)
    .filter((n) => isFile(path.join(themeDir, n)))
    .filter((n) => extensions.includes(ext(n)))
    .filter((n) => !excludePrefixes.some((pre) => stem(n).toLowerCase().startsWith(pre)));
}

// ---------------------------------------------------------------------------
// 1. constants scraped from the Python sources
// ---------------------------------------------------------------------------
function scrapeConstants() {
  const engine = readText(path.join(ROOT, "src", "engine.py"));
  const base = readText(path.join(ROOT, "src", "games", "base.py"));
  const move = readText(path.join(ROOT, "src", "games", "move.py"));
  const targets = readText(path.join(ROOT, "src", "games", "targets.py"));
  const buttons = readText(path.join(ROOT, "src", "games", "buttons.py"));
  const drag = readText(path.join(ROOT, "src", "games", "drag.py"));

  const scalar = (src, name) => {
    const m = src.match(new RegExp(`^${name}\\s*=\\s*(\\d+)`, "m"));
    if (!m) throw new Error(`constant ${name} not found`);
    return Number(m[1]);
  };
  // dict {LEVEL_EASY: <v0>, LEVEL_MEDIUM: <v1>, LEVEL_HARD: <v2>} where <v> is int or (a, b)
  const levelDict = (src, name) => {
    const block = src.match(new RegExp(`${name}\\s*=\\s*{([^}]*)}`, "s"));
    if (!block) throw new Error(`dict ${name} not found`);
    const pick = (level) => {
      const m = block[1].match(new RegExp(`LEVEL_${level}\\s*:\\s*\\(?\\s*(\\d+)\\s*(?:,\\s*(\\d+))?\\s*\\)?`));
      if (!m) throw new Error(`${name}[${level}] not found`);
      return m[2] !== undefined ? [Number(m[1]), Number(m[2])] : Number(m[1]);
    };
    return { easy: pick("EASY"), medium: pick("MEDIUM"), hard: pick("HARD") };
  };

  return {
    VIRTUAL_WIDTH: scalar(engine, "VIRTUAL_WIDTH"),
    VIRTUAL_HEIGHT: scalar(engine, "VIRTUAL_HEIGHT"),
    FPS: scalar(engine, "DEFAULT_FPS"),
    MARGIN_LEFT: scalar(base, "MARGIN_LEFT"),
    MARGIN_TOP: scalar(base, "MARGIN_TOP"),
    PLAY_WIDTH: scalar(base, "PLAY_WIDTH"),
    PLAY_HEIGHT: scalar(base, "PLAY_HEIGHT"),
    LEVELS: ["easy", "medium", "hard"],
    MOVE_TILE: levelDict(move, "TILE_SIZE"),
    TARGET_COUNT: levelDict(targets, "TARGET_COUNT"),
    TARGET_MAX_EDGE: scalar(targets, "TARGET_MAX_EDGE"),
    DOUBLE_CLICK_MS: scalar(targets, "DOUBLE_CLICK_MS"),
    BUTTON_COUNT: levelDict(buttons, "BUTTON_COUNT"),
    BUTTON_MAX_EDGE: scalar(buttons, "BUTTON_MAX_EDGE"),
    DRAG_GRID: levelDict(drag, "GRID"),
    SNAP_DISTANCE: scalar(drag, "SNAP_DISTANCE"),
    BOARD_W: Number(drag.match(/BOARD_W,\s*BOARD_H\s*=\s*(\d+),\s*(\d+)/)[1]),
    BOARD_H: Number(drag.match(/BOARD_W,\s*BOARD_H\s*=\s*(\d+),\s*(\d+)/)[2]),
    BOARD_DX: Number(drag.match(/BOARD_X\s*=\s*MARGIN_LEFT\s*\+\s*(\d+)/)[1]),
    BOARD_DY: Number(drag.match(/BOARD_Y\s*=\s*MARGIN_TOP\s*\+\s*(\d+)/)[1]),
  };
}

// ---------------------------------------------------------------------------
// 2. asset manifest -- one builder per activity, each mirroring its games/*.py
// ---------------------------------------------------------------------------
const MENU_ART = {
  move: ["menu-move1.png", "menu-move.png"],
  click: ["menu-click1.png", "menu-click.png"],
  dblclick: ["menu-dblclick1.png", "menu-dblclick.png"],
  drag: ["menu-puzzle1.png", "menu-puzzle.png"],
  buttons: ["menu-button1.png", "menu-button.png"],
  quit: ["menu-quit.png", "menu-quitter.png"],
};
const ACTIVITY_BG = { move: "move", click: "click", dblclick: "dblclick", drag: "puzzle", buttons: "buttons" };

function coreImages() {
  const names = ["fond-menu.png", "souris.png", "gagne.png", "logo.png", "pysycache.png"];
  for (const pair of Object.values(MENU_ART)) names.push(...pair);
  for (const bg of Object.values(ACTIVITY_BG)) names.push(`fond-${bg}.png`);
  return names.filter((n) => isFile(path.join(ASSETS, "images", n))).map((n) => ref(`images/${n}`));
}

const CORE_SOUNDS = [
  "startup.ogg", "btnmenu.wav", "transition.ogg",
  "youpee.ogg", "yahoo.ogg", "rire.ogg",
  "pop.wav", "double-click.wav", "center.wav", "dragdrop.ogg", "btncoche.ogg",
].filter((n) => isFile(path.join(ASSETS, "sounds", n))).map((n) => ref(`sounds/${n}`));

const FONT = isFile(path.join(ASSETS, "fonts", "FreeSansBold.ttf")) ? ref("fonts/FreeSansBold.ttf") : null;

function themeDirs(suffix) {
  const root = path.join(ASSETS, `themes-${suffix}`);
  return listDir(root)
    .filter((n) => fs.existsSync(path.join(root, n)) && fs.statSync(path.join(root, n)).isDirectory())
    .map((name) => ({ name, dir: path.join(root, name) }));
}

function themeLogo(dir) {
  return isFile(path.join(dir, "logo.png")) ? ref(rel(path.join(dir, "logo.png"))) : null;
}

function buildMove() {
  const out = {};
  for (const { name, dir } of themeDirs("move")) {
    let pics = themeImages(dir, { extensions: [".jpeg", ".jpg"] });
    if (pics.length === 0) pics = themeImages(dir);
    // _load_cover: prefer cache/cache-theme.png, else any cache/*.png
    const cacheDir = path.join(dir, "cache");
    let cover = null;
    if (isFile(path.join(cacheDir, "cache-theme.png"))) cover = path.join(cacheDir, "cache-theme.png");
    else cover = listDir(cacheDir).filter((n) => ext(n) === ".png").map((n) => path.join(cacheDir, n))[0] ?? null;
    out[name] = {
      logo: themeLogo(dir),
      cover: cover ? ref(rel(cover)) : null,
      pictures: pics.map((n) => ref(rel(path.join(dir, n)))),
    };
  }
  return out;
}

// click + double-click share this (targets.py _distinct_theme_images)
function buildTargets(suffix) {
  const out = {};
  const STATE = ["-off", "-on", "-selected"];
  for (const { name, dir } of themeDirs(suffix)) {
    const seen = new Map(); // baseStem -> { plain, off, on, selected } filenames
    // Targets are transparent cut-out sprites (.png).  Skip stray .jpeg photos
    // (e.g. themes-dblclick/butterfly) that Python happens to pick up too.
    for (const n of themeImages(dir, { extensions: [".png"] })) {
      let s = stem(n);
      let slot = "plain";
      for (const suf of STATE) if (s.endsWith(suf)) { s = s.slice(0, -suf.length); slot = suf.slice(1); break; }
      if (s.toLowerCase() === "xxxx") continue; // sea/ placeholder sprite
      if (!seen.has(s)) seen.set(s, {});
      seen.get(s)[slot] ??= n;
    }
    const sprites = [];
    for (const [id, variants] of seen) {
      // one display image per logical sprite; the -on/-off/-selected states
      // aren't used by the game, so don't ship them
      const file = variants.plain ?? variants.off ?? variants.on ?? Object.values(variants)[0];
      if (file) sprites.push({ id, image: ref(rel(path.join(dir, file))) });
    }
    out[name] = { logo: themeLogo(dir), sprites };
  }
  return out;
}

function buildButtons() {
  const out = {};
  for (const { name, dir } of themeDirs("buttons")) {
    const byStem = new Map();
    for (const n of themeImages(dir, { excludePrefixes: ["fond", "logo"] })) byStem.set(stem(n), path.join(dir, n));
    const pairs = [];
    for (const s of [...byStem.keys()].sort((a, b) => a.localeCompare(b))) {
      if (s.endsWith("b")) continue;
      pairs.push({
        rest: ref(rel(byStem.get(s))),
        pressed: byStem.has(s + "b") ? ref(rel(byStem.get(s + "b"))) : null,
      });
    }
    out[name] = { logo: themeLogo(dir), buttons: pairs };
  }
  return out;
}

function buildPuzzle() {
  const out = {};
  for (const { name, dir } of themeDirs("puzzle")) {
    const pics = themeImages(dir, { extensions: [".png", ".jpeg", ".jpg"] })
      .filter((n) => !/^(fond|logo)/i.test(stem(n)));
    out[name] = { logo: themeLogo(dir), pictures: pics.map((n) => ref(rel(path.join(dir, n)))) };
  }
  return out;
}

function buildManifest() {
  const core = coreImages(); // populates referenced
  return {
    core: { images: core, sounds: CORE_SOUNDS, font: FONT },
    themes: {
      move: buildMove(),
      click: buildTargets("click"),
      dblclick: buildTargets("dblclick"),
      buttons: buildButtons(),
      puzzle: buildPuzzle(),
    },
  };
}

// ---------------------------------------------------------------------------
// 3. credits
// ---------------------------------------------------------------------------
function buildCredits() {
  const parts = [];
  for (const suffix of ["move", "click", "dblclick", "buttons", "puzzle"]) {
    for (const { name, dir } of themeDirs(suffix)) {
      const txt = path.join(dir, "credits.txt");
      const html = path.join(dir, "copyright.html");
      let body = "";
      if (isFile(html)) body = readText(html);
      else if (isFile(txt)) body = `<pre>${readText(txt).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]))}</pre>`;
      if (body) parts.push(`<section><h2>themes-${suffix} / ${name}</h2>\n${body}\n</section>`);
    }
  }
  return `<!doctype html><meta charset="utf-8"><title>PySyCache-Modern web -- asset credits</title>
<style>body{font:14px/1.5 system-ui,sans-serif;max-width:52rem;margin:2rem auto;padding:0 1rem}h1{font-size:1.4rem}h2{font-size:1rem;margin-top:2rem;border-top:1px solid #ccc;padding-top:1rem}pre{white-space:pre-wrap}</style>
<h1>Asset credits</h1>
<p>Artwork and sounds are the original PySyCache theme content, each theme under
its own licence.  This file is generated from the per-theme
<code>credits.txt</code> / <code>copyright.html</code> shipped upstream.</p>
${parts.join("\n\n")}
`;
}

// ---------------------------------------------------------------------------
// 4. asset copy + service-worker precache list
// ---------------------------------------------------------------------------
const SHELL = [
  "./", "index.html", "style.css", "manifest.webmanifest", "CREDITS.html",
  "js/main.js", "js/engine.js",
  "js/constants.generated.js", "js/assets.generated.js", "js/sw-precache.generated.js",
  "js/games/index.js", "js/games/base.js", "js/games/move.js", "js/games/targets.js",
  "js/games/click.js", "js/games/dblclick.js", "js/games/drag.js", "js/games/buttons.js",
  "icons/icon-192.png", "icons/icon-512.png", "icons/icon-maskable-512.png",
];

function walkFiles(dir, base = dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).flatMap((n) => {
    const p = path.join(dir, n);
    return fs.statSync(p).isDirectory() ? walkFiles(p, base) : [path.relative(base, p).split(path.sep).join("/")];
  });
}

function copyAssets() {
  let copied = 0;
  for (const r of referenced) {
    const src = path.join(ASSETS, r);
    const dst = path.join(OUT_ASSETS, r);
    if (!isFile(src)) throw new Error(`manifest references missing asset: ${r}`);
    fs.mkdirSync(path.dirname(dst), { recursive: true });
    const s = fs.statSync(src);
    if (!fs.existsSync(dst) || fs.statSync(dst).size !== s.size || fs.statSync(dst).mtimeMs < s.mtimeMs) {
      fs.copyFileSync(src, dst);
      copied++;
    }
  }
  // prune files the manifest no longer references
  let pruned = 0;
  for (const r of walkFiles(OUT_ASSETS)) {
    if (!referenced.has(r)) { fs.rmSync(path.join(OUT_ASSETS, r)); pruned++; }
  }
  return { copied, pruned };
}

// ---------------------------------------------------------------------------
// emit
// ---------------------------------------------------------------------------
function js(obj) {
  return GENERATED_HEADER + `export default ${JSON.stringify(obj, null, 2)};\n`;
}

function writeOrCheck(relFile, content, results) {
  const abs = path.join(WEB, relFile);
  const current = fs.existsSync(abs) ? readText(abs) : null;
  if (CHECK) {
    if (current !== content) results.stale.push(relFile);
    return;
  }
  if (current !== content) {
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content);
    results.wrote.push(relFile);
  }
}

function main() {
  const constants = scrapeConstants();
  const manifest = buildManifest(); // fills `referenced`
  const credits = buildCredits();

  const assetList = [...referenced].sort().map((r) => `assets/${r}`);
  const cacheVersion = createHash("sha1")
    .update(JSON.stringify({ constants, manifest, assetList }))
    .digest("hex")
    .slice(0, 12);
  const precache = {
    CACHE_VERSION: cacheVersion,
    FILES: [...SHELL, ...assetList],
  };

  const results = { wrote: [], stale: [] };
  writeOrCheck("js/constants.generated.js", js(constants), results);
  writeOrCheck("js/assets.generated.js", js(manifest), results);
  writeOrCheck("js/sw-precache.generated.js", js(precache), results);
  writeOrCheck("CREDITS.html", "<!-- GENERATED by web/tools/build.mjs -- do not edit by hand. -->\n" + credits, results);

  if (CHECK) {
    if (results.stale.length) {
      console.error("stale generated files (run `node web/tools/build.mjs`):\n  " + results.stale.join("\n  "));
      process.exit(1);
    }
    console.log("generated files are up to date");
    return;
  }

  const { copied, pruned } = copyAssets();
  console.log(
    `manifest: ${referenced.size} assets referenced, ${copied} copied / ${pruned} pruned in web/assets/\n` +
    `cache version: ${cacheVersion}\n` +
    (results.wrote.length ? `wrote:\n  ${results.wrote.join("\n  ")}` : "generated files already current"),
  );
}

main();
